
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true # SQL 로그 출력
  logging:
    level:
      org:hibernate:SQL: debug
      org:springframework:
        web: debug
        security: debug



